# Stage 1: Builder
FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GOARCH=amd64
RUN go build -ldflags "-s -w" -o /app/inventoryservice ./cmd/inventoryservice

# Stage 2: Runner
FROM alpine:3.19 AS runner
RUN apk add --no-cache ca-certificates

COPY --from=builder /app/inventoryservice /inventoryservice

ENTRYPOINT ["/inventoryservice"]