# docker-compose.yml
version: '3.8'

services:
  db:
    image: postgres:16-alpine 
    restart: always
    environment:
      POSTGRES_DB: orders_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432" 
    volumes:
      - db_data:/var/lib/postgresql/data 
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql 
    healthcheck: 
      test: ["CMD-SHELL", "pg_isready -U postgres -d orders_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db_data: 
