# Stage 1: Builder
FROM golang:1.22-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GOARCH=amd64
RUN go build -ldflags "-s -w" -o /app/inventoryservice ./cmd/inventoryservice

# Stage 2: Runner
FROM alpine/git:2.44.0-r0 AS runner # alpine for certificate for sslmode=disable
# FROM scratch

COPY --from=builder /app/inventoryservice /inventoryservice

ENTRYPOINT ["/inventoryservice"]